### ISSUE TITLE
Check if Users Document already saved with hashed password

### ISSUE THREAD

**Issue by elena-kolomeets** [jrbarhydt/FlaskWebAPI#1]
Hi! First of all, thanks so much for your comprehensive tutorial with well-structured and well-documented code!

I am still at the beginning of it but while I was trying to fill the database with your test data I noticed the unexpected behavior of it. 
I am talking about Users model (`class Users` in `models/users.py`) and overriding `save()` function in particular. It seems that if you try to save a new user and then, after editing fields, save it again, the password hash changes (I compared the hashes myself in the database and also used the `check_pwd_hash` function to compare the hash against the original password. They do not match:

<img src="https://user-images.githubusercontent.com/70906574/109019503-5ad70380-76b9-11eb-9b13-855468ccb07d.PNG" height=400>

In MongoEngine documentation I found this parameter that checks if it is a new document (which should be enough because password field is required in the model, so whenever we create a new user, we create and hash a password):

<img src="https://user-images.githubusercontent.com/70906574/109020234-15670600-76ba-11eb-8c01-20cd22faba59.png" height=400>

And now using it before revoking `generate_pwd_hash` function gets the job done correctly, the hash is only generated once:

<img src="https://user-images.githubusercontent.com/70906574/109020605-6545cd00-76ba-11eb-9990-51d110c4e357.PNG" height=400>

It is a tiny feature but can create some big problems so I wanted to let you know!
I can open a PR with it but if you want to fix it yourself as it's a minor change, that's fine! 

Have a great day ;)

Elena

**Comment by jrbarhydt** [comment]
Great catch Elena! I have updated it. Will go and make sure the gists are updated as well.
