### ISSUE TITLE
Wrong class reference is used during 'authorized' variable initialization in api/meal.py

### ISSUE THREAD

**Issue by Tarabon4ik** [jrbarhydt/FlaskWebAPI#3]
HI everyone! In lines 48 and 108 the api/meal.py:
` authorized: bool = Meals.objects.get(id=get_jwt_identity()).access.admin`
https://github.com/jrbarhydt/FlaskWebAPI/blob/master/api/meal.py#L48
https://github.com/jrbarhydt/FlaskWebAPI/blob/master/api/meal.py#L108

there is a wrong class reference - the lines needs to be changed to:
`authorized: bool = Users.objects.get(id=get_jwt_identity()).access.admin`

and Users class from models/users.py should be imported:
`from models.users import Users`

Otherwise you'll get an error while trying to make a request to function where 'authorized' variable is initialized:

>  During handling of the above exception, another exception occurred:
Traceback (most recent call last):
.
.
.
 File "/var/www/Projects/python/api/meal.py", line 49, in post
    authorized: bool = Meals.objects.get(id=get_jwt_identity()).access.admin
  File "/usr/local/lib/python3.7/site-packages/mongoengine/queryset/base.py", line 271, in get
    raise queryset._document.DoesNotExist(msg)
models.meals.DoesNotExist: Meals matching query does not exist.

And also for those who're using newest version of Flask: the `@jwt_required` decorator is now `@jwt_required()`
https://flask-jwt-extended.readthedocs.io/en/stable/v4_upgrade_guide/#api-changes

And thanks for a great tutorial and source code! Author has done a really good job there!

**Comment by jrbarhydt** [comment]
Great catch, thanks! I committed your changes on this repo and on the gist file.
